export default {
  selectedUnit: { name: 'Unit A' },
  firstname: 'Marvin',
  middlename: 'Julius',
  lastname: 'Buckwheat',
  address: '4321 Lets Jam Ave',
  city: 'Royal',
  state: 'Mississippi',
  zip: 34322,
  homephone: '749-234-2342',
  workphone: '234-234-5522',
  cellphone: '213-234-3455',
  email: 'MJ@buckvalley.org',
  social: '222-353-2424',
  bday: '22/52/4211',
  license: 'S-999-234-233-343',
  licenseimg: 'url',
  carmake: 'Honda',
  carmodel: 'Bandwagon',
  caryear: '1938',
  currentEmployer: 'Rally Car Mfg',
  currentEmployerPhone: '349-2333-3521',
  currentEmployerAddress: '3432 Bad Luck Drive',
  currentEmploymentLength: 1,
  currentPosition: 'Ball Boy',
  currentMonthlyIncome: '1820',
  currentSupervisor: 'Rick Mcnally',
  currentEmployerEmail: 'rm@badluck.org',
  previousEmployer: 'Quicksand Saviours',
  previousEmployerPhone: '348-033-2422',
  previousEmployerAddress: 'Sandy Lane',
  previousEmploymentLength: 12,
  previousPosition: 'Duster',
  previousMonthlyIncome: '1299',
  previousSupervisor: 'Viktor Patnov',
  previousEmployerEmail: 'vk@sandyboys.net',
  otherIncome: 'yes',
  incomeSources: 'tractor repair',
  incomeFromSources: '189',
  previousRentalThreshold: 3,
  currentLandlord: 'Bosco Phillips',
  currentYearsLived: 2,
  currentLandlordPhone: '344-234-2345',
  currentLandlordEmail: 'bp@rentalcity.net',
  currentLandlordAddress: '533 Killjoy rd.',
  currentLandlordCity: 'Mexico City',
  currentLandlordState: 'Mexico',
  currentReasonLeaving: 'Didnt like the commute',
  currentLeaseExp: '12/24/2442',
  secondLastLandlord: 'Maisel West',
  secondLastYearsLived: 2,
  secondLastLandlordPhone: '234-234-2352',
  secondLastLandlordEmail: 'jordandoes@west.com',
  secondLastLandlordAddress: '2342 Nowhere lane',
  secondLastLandlordCity: 'Driveby',
  secondLastLandlordState: 'Rhode Island',
  secondLastLeaseExp: '53/24/2342',
  secondLastReasonLeaving: 'Bad Landlord Shitty Time',
  thirdLastLandlord: '',
  thirdLastYearsLived: null,
  thirdLastLandlordPhone: '',
  thirdLastLandlordEmail: '',
  thirdLastLandlordAddress: '',
  thirdLastLandlordCity: '',
  thirdLastLandlordState: '',
  thirdLastLeaseExp: '',
  thirdLastReasonLeaving: '',
  eviction: 'yes',
  explain: 'Didnt feel like paying.',
  occupantList: [
    {
      firstName_1: 'Yosef',
      middleName_1: 'A',
      lastName_1: 'Harmenedes',
      socialSecurity_1: '223-245-2234',
      relationship_1: 'Brother',
    },
    {
      firstName_2: 'Yolinda',
      middleName_2: 'B',
      lastName_2: 'Harmenedes',
      socialSecurity_2: '223-243-2234',
      relationship_2: 'sister',
    },
    {
      firstName_3: 'Yarline',
      middleName_3: 'G',
      lastName_3: 'Harmenedes',
      socialSecurity_3: '223-242-2234',
      relationship_3: 'mother',
    },
    {
      firstName_4: 'Yandy',
      middleName_4: 'L',
      lastName_4: 'Harmenedes',
      socialSecurity_4: '423-245-2234',
      relationship_4: 'Father',
    },
    {
      firstName_5: 'Yavin',
      middleName_5: '4',
      lastName_5: 'Harmenedes',
      socialSecurity_5: '223-245-2434',
      relationship_5: 'Grandpapa',
    },
  ],
  voucher: 'no',
  occupantCount: 5,
  desiredMovein: '23/23/2522',
  cosigner: 'no',
  agency: '',
  agencyPhone: '',
  caseWorker: '',
  creditors: 'Ace Hardware',
  policeCalled: 4,
  sexOffender: 'no',
  criminalOffense: 'no',
  explainCriminal: '',
  explainSummons: '',
  summoned: 'no',
  explainBankrupt: '',
  bankrupt: 'no',
  pets: 'no',
  relativeFirstName: 'Yormandy',
  relativeLastName: 'Jillz',
  relativeAddress: '2222 Yunny Lane',
  relativePhone: '234-243-2522',
  relativeEmail: 'YJ@yj.net',
  relativeState: 'WI',
  relativeCity: 'Green Bay',
  datestamp: '23/23/5223',
  consent: true,
  signature: 'Marvin Buckwheat Jr III',
  submitted: false,
  validationErrors: {},
};
