[build]

  base = "."

  publish = "dist/"

  # Default build command.
  command = "npm run build"


[context.branch-deploy]
    command="vue-tsc --noEmit && vite build --mode dev"



[dev]
    functions = "netlify/functions"
    functionsPort = 7000